name: CI/CD

on:
  push:
    branches:
      - master
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setting .env
        run: |
          echo "REACT_APP_END_POINT=${{secrets.REACT_APP_END_POINT}}" >> .env
          echo "REACT_APP_TEST_POINT=${{secrets.REACT_APP_TEST_POINT}}" >> .env
          cat .env

      - run: yarn install
      - run: echo SUCCESS
      - run: yarn test
      - run: CI=false yarn build
      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'build'
